# Auto-generated by start.sh from .env — do not edit manually
global:
  scrape_interval: __PROMETHEUS_SCRAPE_INTERVAL__
  evaluation_interval: 15s
  external_labels:
    monitor: 'sxt-validator-dashboard'

scrape_configs:
  # -------------------------------------------------------
  # 1. Native Substrate Prometheus metrics (:9615)
  #    block_height, peers, grandpa, libp2p, sync, proposer
  # -------------------------------------------------------
  - job_name: 'sxt-node'
    scrape_interval: 10s
    static_configs:
      - targets: ['__SXT_PROMETHEUS_TARGET__']
        labels:
          chain: 'sxt-mainnet'

  # -------------------------------------------------------
  # 2. Custom SXT exporter (:9101)
  #    RPC-derived: sync state, BABE authorship, GRANDPA
  #    round state, attestations, runtime version
  # -------------------------------------------------------
  - job_name: 'sxt-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['sxt-exporter:__SXT_EXPORTER_PORT__']
        labels:
          chain: 'sxt-mainnet'

  # -------------------------------------------------------
  # 3. Host hardware metrics (node_exporter :9100)
  # -------------------------------------------------------
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['__NODE_EXPORTER_TARGET__']
        labels:
          instance: 'sxt-validator-host'

  # -------------------------------------------------------
  # 4. Prometheus self-monitoring
  # -------------------------------------------------------
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
