apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: '15s'
      httpMethod: POST

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    editable: false
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: sxt
      username: $CLICKHOUSE_USER
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD
